version: '3.8'

services:
  wordpress:
    image: wordpress
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin@123
    volumes:
      - ./:/var/www/html/
    depends_on:
      - wordpress_db
    networks:
      - wordpress_network

  wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: admin@123
    depends_on:
      - wordpress_db
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
